Script started on 2020-05-07 09:31:13-0500
]0;jacob@DESKTOP-QKT72KA: ~/214/labs/extraCredit[01;32mjacob@DESKTOP-QKT72KA[00m:[01;34m~/214/labs/extraCredit[00m$ clojure
Clojure 1.10.1
user=> (fn [x] (+ x x))
#object[user$eval136$fn__137 0x9255c05 "user$eval136$fn__137@9255c05"]
user=> ((fn [x] (+ x x)) 21)
42
user=> ((fn [x y] (+ (* x x))  (* y y))) 3 4)
25
user=> 
]0;jacob@DESKTOP-QKT72KA: ~/214/labs/extraCredit[01;32mjacob@DESKTOP-QKT72KA[00m:[01;34m~/214/labs/extraCredit[00m$ exit

Script done on 2020-05-07 09:33:20-0500
