Script started on 2020-05-07 09:44:35-0500
]0;jacob@DESKTOP-QKT72KA: ~/214/labs/extraCredit[01;32mjacob@DESKTOP-QKT72KA[00m:[01;34m~/214/labs/extraCredit[00m$ clojure
Clojure 1.10.1
user=> (def squareSquare #(* (* % %) (* % %)))
#'user/squareSquare
user=> (squareSquare 2)
16
user=> (squareSqau  uare 3)
81
user=> 
]0;jacob@DESKTOP-QKT72KA: ~/214/labs/extraCredit[01;32mjacob@DESKTOP-QKT72KA[00m:[01;34m~/214/labs/extraCredit[00m$ exit

Script done on 2020-05-07 09:45:01-0500
