Sum: Sum.class
ArraySum: ArraySum.class
ThreadedArraySum: ThreadedArraySum.class

Sum.class: Sum.java
	javac -deprecation Sum.java

ArraySum.class: ArraySum.java
	javac -deprecation ArraySum.java

ThreadedArraySum.class: ThreadedArraySum.java
	javac -deprecation ThreadedArraySum.java

clean:
	rm -f *.class *~ *#

