"average.sm is a Smalltalk 'program' to test the average method.
  Dr. Adams, CS 214 at Calvin College.
  Precondition: anArray is an array of numbers.
  Output: the average of the values in anArray.
"
| anArray |

"Replace this line with an initialization of anArray"

Transcript clear;
             cr;
             show: 'The average is ';
             show: anArray average printString;
             cr.

